Repository likelion4th-React-LAB15/final-project, pull requests merged in 2023-03, with the labels that each got.

#9 feature: 로그인 페이지 마크업 및 기능 구현 완료 #3 #5 #7 #8
  final-cra/package-lock.json
  final-cra/package.json
  final-cra/public/index.html
  final-cra/public/style/global.css
  final-cra/src/@service/app.js
  final-cra/src/@service/auth/index.js
  final-cra/src/@service/auth/useAuthState.js
  final-cra/src/@service/auth/useSignIn.js
  final-cra/src/@service/auth/useSignOut.js
  final-cra/src/@service/auth/useSignUp.js
  final-cra/src/app/App.jsx
  final-cra/src/components/Auth.js
  final-cra/src/components/GlobalStyle.js
  final-cra/src/components/Title.jsx
  final-cra/src/components/user/UserButton.jsx
  final-cra/src/components/user/UserForm.jsx
  final-cra/src/components/user/UserInput.jsx
  final-cra/src/components/user/index.js
  final-cra/src/index.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/LogIn.jsx
  final-cra/src/pages/SignUp.jsx
  final-cra/src/pages/index.js
  final-cra/src/style/theme.js
Labels: 🐞 BugFix, 🗿 Chore, ✨ Feature, 🌈 Style

#16 feature: header, visual, section01 및 기능 구현 완료
  final-cra/package-lock.json
  final-cra/package.json
  final-cra/src/app/App.jsx
  final-cra/src/assets/images/backgorund-01 .webp
  final-cra/src/assets/images/background-01.webp
  final-cra/src/assets/images/logo-on.png
  final-cra/src/components/CustomBtn.jsx
  final-cra/src/components/CustomInput.jsx
  final-cra/src/components/GlobalStyle.js
  final-cra/src/components/Header.jsx
  final-cra/src/components/HeaderWave.jsx
  final-cra/src/components/SectionOne.jsx
  final-cra/src/components/Visual.jsx
  final-cra/src/components/smoothscroll/SmoothScroll.jsx
  final-cra/src/index.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/LogIn.jsx
  final-cra/src/pages/SignUp.jsx
Labels: ✨ Feature

#17 Feature: 메인페이지 Section, Footer 및 About 페이지 구현 완료
  final-cra/package-lock.json
  final-cra/package.json
  final-cra/public/index.html
  final-cra/public/style/global.css
  final-cra/src/app/App.jsx
  final-cra/src/assets/icons/btn-arrow-down-white.svg
  final-cra/src/assets/icons/btn-home.svg
  final-cra/src/assets/icons/btn-search-white.svg
  final-cra/src/assets/icons/logo-off.png
  final-cra/src/assets/icons/logo-on.png
  final-cra/src/assets/images/aboutbg-01.jpg
  final-cra/src/assets/images/aboutbg-02.jpg
  final-cra/src/assets/images/aboutbg-03.jpg
  final-cra/src/assets/images/background-09.webp
  final-cra/src/assets/images/fix-siheky-bottom.svg
  final-cra/src/components/FilmList/FilmList.jsx
  final-cra/src/components/Footer/Footer.jsx
  final-cra/src/components/Footer/FooterAddress.jsx
  final-cra/src/components/Footer/FooterGnb.jsx
  final-cra/src/components/Header.jsx
  final-cra/src/components/HeaderWave.jsx
  final-cra/src/components/SectionOne.jsx
  final-cra/src/components/Siheky/Siheky.jsx
  final-cra/src/components/Siheky/SihekyAnimationObject.jsx
  final-cra/src/components/Siheky/SihekyContents.jsx
  final-cra/src/components/Siheky/SihekyInner.jsx
  final-cra/src/components/Visual.jsx
  final-cra/src/components/Wave/Wave.jsx
  final-cra/src/components/about/AboutItem.jsx
  final-cra/src/components/about/AboutItemDesc.jsx
  final-cra/src/components/about/AboutItemImage.jsx
  final-cra/src/components/about/AboutList.jsx
  final-cra/src/components/about/BigFont.jsx
  final-cra/src/components/about/index.js
  final-cra/src/components/closingContent/ClosingContents.jsx
  final-cra/src/components/closingContent/ClosingDesc.jsx
  final-cra/src/components/closingContent/ClosingSub.jsx
  final-cra/src/components/closingContent/ClosingSubDesc.jsx
  final-cra/src/components/closingContent/ClosingTitle.jsx
  final-cra/src/components/closingContent/ClosingTitleBold.jsx
  final-cra/src/components/closingContent/ClosingTitleLine.jsx
  final-cra/src/components/closingContent/index.js
  final-cra/src/components/smoothScroll/SmoothScroll.jsx
  final-cra/src/components/subNav/SubNav.jsx
  final-cra/src/components/subNav/SubNavItemList.jsx
  final-cra/src/components/subNav/SubNavLnb.jsx
  final-cra/src/components/subNav/SubNavSearchIcon.jsx
  final-cra/src/pages/About.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/index.js
Labels: 🗿 Chore, ✨ Feature, 🔨 Refactor

#21 feat: 회원가입 페이지 기능 구현 #14 #20
  final-cra/.gitignore
  final-cra/package-lock.json
  final-cra/package.json
  final-cra/src/@service/auth/index.js
  final-cra/src/@service/auth/useSignIn.js
  final-cra/src/@service/auth/useSignUp.js
  final-cra/src/@service/firestore/index.js
  final-cra/src/@service/firestore/useCreateAuthUser.jsx
  final-cra/src/@service/firestore/useCreateData.js
  final-cra/src/@service/firestore/useDataState.js
  final-cra/src/assets/icons/check.svg
  final-cra/src/assets/icons/radio.svg
  final-cra/src/components/Border.jsx
  final-cra/src/components/Footer/Footer.jsx
  final-cra/src/components/Siheky/Siheky.jsx
  final-cra/src/components/user/UserBirth.jsx
  final-cra/src/components/user/UserButton.jsx
  final-cra/src/components/user/UserCheckBox.jsx
  final-cra/src/components/user/UserInput.jsx
  final-cra/src/components/user/UserLabel.jsx
  final-cra/src/components/user/UserRadio.jsx
  final-cra/src/components/user/index.js
  final-cra/src/index.jsx
  final-cra/src/pages/About.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/LogIn.jsx
  final-cra/src/pages/SignUp.jsx
Labels: 🐞 BugFix, ✨ Feature

#37 feat: Reservation 페이지와 firebase db 연동 및 로딩스피너 제작 #27 #33 #35
  final-cra/.storybook/main.js
  final-cra/.storybook/preview.js
  final-cra/package-lock.json
  final-cra/package.json
  final-cra/src/@service/auth/useSignUp.js
  final-cra/src/assets/icons/loading-spinner.svg
  final-cra/src/components/Footer/Footer.jsx
  final-cra/src/components/Loading.jsx
  final-cra/src/components/Reservation/RoomInfoCard.js
  final-cra/src/components/Siheky/Siheky.jsx
  final-cra/src/components/user/UserInput.jsx
  final-cra/src/pages/About.jsx
  final-cra/src/pages/Community.jsx
  final-cra/src/pages/Guam.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/LogIn.jsx
  final-cra/src/pages/Notice.jsx
  final-cra/src/pages/Reservation.jsx
  final-cra/src/pages/Reservation1.jsx
  final-cra/src/pages/Reservation2.jsx
  final-cra/src/pages/Reservation3.jsx
  final-cra/src/pages/Reservation4.jsx
  final-cra/src/pages/Saipan.jsx
  final-cra/src/pages/SignUp.jsx
  final-cra/src/stories/Button.jsx
  final-cra/src/stories/Button.stories.jsx
  final-cra/src/stories/Header.jsx
  final-cra/src/stories/Header.stories.jsx
  final-cra/src/stories/Introduction.stories.mdx
  final-cra/src/stories/Page.jsx
  final-cra/src/stories/Page.stories.jsx
  final-cra/src/stories/assets/code-brackets.svg
  final-cra/src/stories/assets/colors.svg
  final-cra/src/stories/assets/comments.svg
  final-cra/src/stories/assets/direction.svg
  final-cra/src/stories/assets/flow.svg
  final-cra/src/stories/assets/plugin.svg
  final-cra/src/stories/assets/repo.svg
  final-cra/src/stories/assets/stackalt.svg
  final-cra/src/stories/button.css
  final-cra/src/stories/header.css
  final-cra/src/stories/page.css
Labels: ✨ Feature

#41 Refactor: 성능 개선 및 접근성 고려 / Modal 팝업 제작
  final-cra/public/index.html
  final-cra/src/assets/icons/btn-close-modal.svg
  final-cra/src/assets/images/background-04.webp
  final-cra/src/assets/images/background-05.webp
  final-cra/src/assets/images/background-06.webp
  final-cra/src/assets/images/background-07.webp
  final-cra/src/assets/images/background-08.webp
  final-cra/src/assets/images/background-09.webp
  final-cra/src/assets/images/background-10.webp
  final-cra/src/assets/images/background-11.webp
  final-cra/src/assets/images/background-12.webp
  final-cra/src/components/FilmList/FilmList.jsx
  final-cra/src/components/Footer/FooterAddress.jsx
  final-cra/src/components/MainSection/SectionOne.jsx
  final-cra/src/components/Modal/Modal.jsx
  final-cra/src/components/ModalPortal/ModalPortal.js
  final-cra/src/components/Visual/Visual.jsx
  final-cra/src/pages/Community.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/Notice.jsx
  final-cra/src/pages/SignUp.jsx
Labels: ✨ Feature, 🔨 Refactor

#43 feat: Reservation 4 페이지 제작
  final-cra/src/assets/icons/MasterCard.png
  final-cra/src/assets/icons/Visa.png
  final-cra/src/assets/icons/checked.png
  final-cra/src/assets/icons/notChecked.png
  final-cra/src/components/Reservation/Accordion.js
  final-cra/src/components/Reservation/AccordionHandle.js
  final-cra/src/components/Reservation/AccordionPanel.js
  final-cra/src/components/Reservation/InputUserInfo.js
  final-cra/src/components/Reservation/OptionSelect.js
  final-cra/src/components/Reservation/ReservationCalendar.js
  final-cra/src/components/Reservation/RoomInfoCard.js
  final-cra/src/pages/Reservation1.jsx
  final-cra/src/pages/Reservation3.jsx
  final-cra/src/pages/Reservation4.jsx
Labels: ✨ Feature

#44 refactor: lazy, Suspense를 이용하여 비동기적 라우팅 시도
  final-cra/src/app/App.jsx
  final-cra/src/components/Header/Header.jsx
  final-cra/src/components/Reservation/ReservationCalendar.js
  final-cra/src/index.jsx
  final-cra/src/pages/Home.jsx
  final-cra/src/pages/LogIn.jsx
  final-cra/src/pages/Reservation3.jsx
  final-cra/src/pages/SignUp.jsx
Labels: 🔨 Refactor

#47 feat: Modal 컴포넌트 조건부 렌더링 및 Reservation4에 추가
  final-cra/src/@service/auth/useSignIn.js
  final-cra/src/components/Header/Header.jsx
  final-cra/src/components/Modal/Modal.jsx
  final-cra/src/pages/Reservation4.jsx
Labels: ✨ Feature
