Repository likelion4th-React-LAB15/final-project, pull requests merged in 2023-04, with the labels that each got.

#53 Feature/49 main video keyboard accessibility
  final-cra/src/components/Button/Video/VideoButton.jsx
  final-cra/src/components/Video/Video.jsx
  final-cra/src/components/Visual/Visual.jsx
Labels: ✨ Feature, 🥰 Accessibility

#55 Accessibility: A11yHidden, Label 컴포넌트 추가 & 결제페이지 A11Hiden Label 추가
  final-cra/src/components/A11yHidden/A11yHidden.jsx
  final-cra/src/components/Label/Label.jsx
  final-cra/src/components/Reservation/InputUserInfo.jsx
  final-cra/src/pages/Reservation4.jsx
Labels: 🥰 Accessibility

#56 refactor: 메인 섹션 애니메이션 정지/재시작 기능 구현 #52
  final-cra/src/components/MainSection/PlayButton.jsx
  final-cra/src/components/MainSection/SectionOne.jsx
Labels: 🔨 Refactor
